/*
*   Copyright (c) 2024 Arcology Network

*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.

*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package statestore

import (
	"math"

	indexer "github.com/arcology-network/common-lib/storage/indexer"

	statecell "github.com/arcology-network/common-lib/crdt/statecell"

	// interfaces "github.com/arcology-network/state-engine/interfaces"
	crdtcommon "github.com/arcology-network/common-lib/crdt/common"
)

// An index by path, transitions have the same path will be put together in a list
// This index will be used for apply transitions on the original state. So all the transitions
// should be put into this index.
func PathIndexer(store crdtcommon.ReadOnlyStore) *indexer.UnorderedIndexer[string, *statecell.StateCell, []*statecell.StateCell] {
	return indexer.NewUnorderedIndexer(
		nil,

		// Return the key for the path if it is missing.
		func(v *statecell.StateCell) (string, bool) {
			return *v.GetPath(), true
		},

		// The function to update the value when it exists.
		func(k string, v *statecell.StateCell) []*statecell.StateCell {
			if v.Value() != nil {
				v.Value().(crdtcommon.Type).Preload(k, store)
			}
			return []*statecell.StateCell{v}
		},

		func(_ string, v *statecell.StateCell, vals *[]*statecell.StateCell) { *vals = append(*vals, v) },
	)
}

// An index by tx number, transitions have the same tx number will be put together in a list.
// This index will be used to remove the transitions generated by the conflicting transactions.
// So, the immutable transitions should not be put into this index.
func TxIndexer(_ crdtcommon.ReadOnlyStore) *indexer.UnorderedIndexer[uint64, *statecell.StateCell, []*statecell.StateCell] {
	return indexer.NewUnorderedIndexer(
		nil,
		func(v *statecell.StateCell) (uint64, bool) {
			if !v.IfSkipConflictCheck() {
				return v.GetTx(), true
			}
			return math.MaxUint32, false
		},
		func(_ uint64, v *statecell.StateCell) []*statecell.StateCell { return []*statecell.StateCell{v} },
		func(_ uint64, v *statecell.StateCell, vals *[]*statecell.StateCell) { *vals = append(*vals, v) },
	)
}
