/*
*   Copyright (c) 2025 Arcology Network

*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.

*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package noncommutativecodec

import (
	"math/big"

	"github.com/arcology-network/common-lib/codec"
	noncommutative "github.com/arcology-network/common-lib/crdt/noncommutative"
	"github.com/ethereum/go-ethereum/rlp"
)

type BytesRLP struct{ noncommutative.Bytes }

// big int can take on arbitrary length, but will remove the leading zeros.
// This isn't a problem in the original Ethereum implementation because
// it has a fixed word size of 32 bytes. The leading zeros can be restored by copying the bytes
// back to a 32 byte slice. However, we don't have a fixed word size for entries generated by Arcology's extensions,
// so we need to encode the length of the byte slice.
func (this *BytesRLP) Encode() ([]byte, error) {
	raw := []byte(this.Bytes.Value().(codec.Bytes))
	return rlp.EncodeToBytes(new(big.Int).SetBytes(raw))
}

func (this *BytesRLP) Decode(buffer []byte) (any, error) {
	var out []byte
	if err := rlp.DecodeBytes(buffer, &out); err != nil {
		return nil, err
	}
	return noncommutative.NewBytes(out), nil
}
